"""Render a self-contained report from saved post-hoc measurements."""
import json
from pathlib import Path

def render_report(out):
    out=Path(out);m=json.loads((out/'metrics.json').read_text());names=m['names'];ti=m['true_indices'];sp=m['spurious_indices']
    parts=[]
    def add(s):parts.append(s+'\n')
    def table(headers,rows):
        def fmt(x):return f'{x:.6g}' if isinstance(x,float) else str(x)
        add('| '+' | '.join(headers)+' |\n| '+' | '.join(['---']*len(headers))+' |\n'+'\n'.join('| '+' | '.join(fmt(x) for x in row)+' |' for row in rows))
    add('# Phase 19B: what changes between 5k and 10k?\n')
    add('The best-supported interpretation is **mixed, with a strong target-fidelity component and improved cancellation of transport/diffusion errors**. The regression becomes Burgers-like without improved global conditioning or disappearance of spurious alternatives. At 5k even unconstrained least squares on the learned fields favors weak transport; by 10k its optimum is close to the trained head and Burgers coefficients. Thus the difference is not only failure of the symbolic optimizer to solve the same regression problem. This is an observational comparison, not a causal explanation of the 8k–9k dynamics.')
    add('## Scope and reproducible method\n')
    add(f'Branch: `sami`. Source: `/home/ghost/ghost/pde_stuff/run_results/phase19b_long_horizon_control/`. Checkpoints: 5000, 10000, and supplementary 20000. Shared grid: {m["grid_shape"][0]} times × {m["grid_shape"][1]} spatial points, 64,512 equally weighted observations. Coordinates and clean observations are loaded from the archived matched inputs, in time-major order. The original sampled times include endpoints and alternating interior solver times; these are sample norms, not quadrature-weighted continuum norms. Physical x is periodic in [0,2π), t spans [0,1].')
    add('“Reference” means the saved numerical Burgers solution, not an analytic continuum solution. Reference spatial derivatives use the generator’s centered periodic differences; reference u_t is defined as −u·u_x + 0.02u_xx. Consequently exact-reference regression recovery is an algebraic consistency check, not independent validation of temporal discretization. Network autodiff and reference finite differences are different operators near sharp gradients. No new rollout, model fitting, training, or sweep is performed; least squares is a direct post-hoc linear solve.')
    add('Primitive evaluation and metrics use `utils.derivative_utils.evaluate_model_primitive_features` via `evaluate_diagnostic_fields`, and `evaluate_primitive_feature_metrics` via the existing `field_metrics` helper. Active primitives are `[u,u_x,u_xx]`. Nine-term ordering is verified against `prog.minimal_symnet.product_term_dict` and the existing `utils.burgers_recoverability.library`:')
    add('`'+'; '.join(names)+'`. No intercept is added. Two-support fits explicitly use `[u*u_x,u_xx]`; all nine-term displays retain the canonical ordering.')
    add('Linear algebra uses float64 on float32 model evaluations. Raw geometry uses physical columns A. Normalized geometry uses Z_j=A_j/||A_j||₂ (no centering); ZᵀZ is the cosine Gram matrix. Pearson matrices, separately stored in metrics.json, subtract means. Raw Gram is AᵀA/N. Raw columns have different physical units, so raw condition numbers are unit-dependent. This diagnostic normalization is not the fixed primitive scaling used during training.')
    add('SVD solves Zβ≈y with relative singular-value cutoff 1e−12; physical coefficients are β_j/||A_j||₂. No normal-equation inversion is used. Orthogonal bases are thin SVD bases of unit-column matrices with the same cutoff. Principal angles are acos of singular values of Q_trueᵀQ_spurious. Rank sensitivity is reported at relative cutoffs 1e−12, 1e−8, 1e−4, 1e−2; stable rank is ||A||_F²/||A||₂². Projection energy is ||QQᵀe||²/||e||². True and spurious projections overlap and must not be added. The reference true-support residual is numerical roundoff, so its explained fraction is undefined and recorded as null.')
    add('## A. Field, derivative, true-term, and RHS fidelity\n')
    table(['state','quantity','MSE','RMSE','relative L2','cosine','Pearson','RMS prediction','RMS reference'],[[r[k] for k in ['state','quantity','mse','rmse','rel_l2','cosine','pearson','rms_prediction','rms_reference']] for r in m['fidelity']])
    add('`rhs` is the Burgers combination evaluated on learned fields, not the trained symbolic RHS. u_xx is both a primitive and the true diffusion feature; its row serves both purposes. By 10k, u_xx relative error is still 0.660 and transport-term relative error is 0.364. However, u_t relative error falls 0.918→0.222 and cosine rises 0.432→0.978. Its RMS rises 0.252→0.876 toward reference 0.976: the early head sees a strongly attenuated, poorly aligned target. All derivatives becoming accurate is too strong a description.')
    add('## B. Raw and normalized feature geometry\n')
    table(['state','raw κ','unit-column κ','raw ranks (1e−12/1e−8/1e−4/1e−2)','normalized ranks','stable rank raw / normalized','principal angles (degrees)'],[[s,g['raw']['condition'],g['normalized']['condition'],' / '.join(map(str,g['raw']['ranks'].values())),' / '.join(map(str,g['normalized']['ranks'].values())),f"{g['raw']['stable_rank']:.4g} / {g['normalized']['stable_rank']:.4g}",', '.join(f'{v:.4f}' for v in g['true_spurious_principal_angles_degrees'])] for s,g in m['geometry'].items()])
    add('Every library has numerical rank 9 at 1e−12. Normalized conditioning gets slightly worse (5.812→6.502), as does raw conditioning (2749→8061); the reference is still more ill-conditioned in either representation. Smallest true/spurious principal angle shrinks 31.58°→27.27° (reference 23.36°): subspaces become closer, not better separated. No numerical rank transition is present.')
    table(['feature']+[s+' RMS / L2 norm' for s in m['geometry']],[[n]+[f"{g['column_rms'][i]:.6g} / {g['column_norms'][i]:.6g}" for g in m['geometry'].values()] for i,n in enumerate(names)])
    for s,g in m['geometry'].items():
        add(f'**{s} singular values**, descending. Raw: '+', '.join(f'{v:.7g}' for v in g['raw']['singular_values'])+'. Unit-column: '+', '.join(f'{v:.7g}' for v in g['normalized']['singular_values'])+'.')
    table(['state','true term','spurious term','cosine','Pearson'],[[r[k] for k in ['state','true_term','spurious_term','cosine','pearson']] for r in m['alignments'] if r['state']!='20000'])
    add('The strongest single spurious alignment for both true terms is u_x*u_xx. Its transport cosine magnitude decreases 0.745→0.647, but diffusion alignment increases 0.794→0.879 (reference 0.915). Some pairwise alignment improves, but false alternatives do not generally disappear. Full 9×9 raw Gram, cosine Gram, and Pearson matrices are in metrics.json and the labeled heatmaps.')
    table(['state','cosine(u*u_x,u_xx)','Pearson(u*u_x,u_xx)'],[[s,g['normalized_gram'][ti[0]][ti[1]],g['pearson'][ti[0]][ti[1]]] for s,g in m['geometry'].items()])
    add('## C. Identifiability and support-restricted fits\n')
    add('“Predicted” fits use learned features and learned u_t; “reference” target uses learned features with reference u_t (except the reference-state control); “predicted_on_reference_features” holds reference columns fixed and uses that checkpoint’s learned target. Target substitutions are algebraic comparisons, not training interventions. Coefficient error is physical Euclidean distance from truth, with term-specific units; it is not a dimensionless measure of PDE contribution.')
    table(['state','target','support','transport','diffusion','residual L2','residual MSE','relative residual','coefficient error'],[[r['state'],r['target'],r['support'],r['coefficients'][ti[0]] if r['support']=='full' else r['coefficients'][0],r['coefficients'][ti[1]] if r['support']=='full' else r['coefficients'][1],r['residual_norm'],r['residual_mse'],r['residual_relative_l2'],r['coefficient_error']] for r in m['fits']])
    add('All physical full-library coefficients:')
    table(['state','target']+names,[[r['state'],r['target']]+r['coefficients'] for r in m['fits'] if r['support']=='full'])
    table(['state','target','true-support MSE minus full MSE','fraction of true-support residual explained by additional spurious directions'],[[r['state'],r['target'],r['true_minus_full_mse'],r['incremental_spurious_fraction_of_true_residual']] for r in m['fits'] if 'true_minus_full_mse' in r])
    add('The last fraction uses S_perp=(I−P_true)S: it measures additional residual fitting after the true support, rather than double-counting overlapping spans. At 5k, spurious directions remove 87.4% of the best true-support residual; at 10k they remove 95.0%. The absolute MSE benefit declines 0.03944→0.02874, but ambiguity does not disappear. At 5k, the full learned regression transport is −0.1299; replacing only the target gives −0.8314 (with high residual 0.6128). Conversely, reference features with the 5k target still yield −0.1061. By 10k these three transports are −0.9041, −1.0115, and −0.8729. Target fidelity is therefore a prominent algebraic contributor; feature fidelity also matters greatly for residual accuracy.')
    add('The unrestricted LS head has coefficient error 0.8909→0.1220. The trained head transport is −0.03784→−0.89910, and its full-grid residual MSE is 0.009611→0.001567, compared with LS 0.005694→0.001510. The 10k head is close to the unconstrained residual optimum; the 5k learned regression itself does not favor Burgers. Full LS is a relaxation: one-product MinimalSymNet cannot represent every nine-term quadratic vector, and these fits do not establish optimization reachability or exact support selection.')
    add('## D. Error geometry and cancellation\n')
    add('Define e_t=û_t−u_t, e_c=(ûû_x)−(uu_x), e_d=û_xx−u_xx. RHS error is e_R=−e_c+0.02e_d, and closure error at true coefficients is r_B=e_t−e_R. The physical diffusion contribution is 0.02e_d, not unweighted e_d.')
    table(['state','cos(e_t,e_c)','cos(e_t,e_d)','cos(e_c,e_d)','RHS error MSE','closure MSE','RHS cancellation ratio','target/RHS cancellation ratio'],[[s,e['pairwise_cosine']['e_t,e_transport'],e['pairwise_cosine']['e_t,e_diffusion'],e['pairwise_cosine']['e_transport,e_diffusion'],e['rhs_error_mse'],e['closure_mse'],e['rhs_cancellation_ratio'],e['target_rhs_error_cancellation_ratio']] for s,e in m['errors'].items()])
    add('RHS cancellation ratio = ||−e_c+0.02e_d||²/(||e_c||²+||0.02e_d||²): 0.370→0.209, supporting stronger spatial-term cancellation. RHS relative error nonetheless remains 0.397 at 10k; it is not exact. The analogous target/RHS ratio rises 0.260→0.584, so improved target-to-RHS error cancellation is not the explanation. Closure MSE at exact Burgers coefficients is still 0.1147 at 10k, much larger than fitted full-library MSE 0.001510; coefficient adjustment and spurious corrections remain consequential.')
    table(['state','error','span','error L2','projected L2','projected energy fraction','unprojected L2'],[[r[k] for k in ['state','error','space','norm','projected_norm','energy_fraction','residual_norm']] for r in m['projections'] if r['state']!='20000'])
    add('At 5k, most individual errors lie outside the spurious span (projected energies: e_t 11.0%, e_c 2.8%, e_d 21.6%); it would be misleading to claim most derivative error is cheaply representable there. At 10k those fractions increase to 35.2%, 18.4%, 58.6%. Absolute projected e_t norm falls 75.43→32.59, while projected transport and diffusion error norms actually increase (49.17→56.57 and 5353→6510). The smaller remaining closure error is much more spurious-aligned (46.2%→93.7%), explaining why relatively small spurious coefficients can still greatly lower PDE residual. Span alignment alone is not a parameter-cost measure.')
    add('Single-column projection of e_t (columns overlap; fractions do not sum):')
    table(['state','column','cosine','projection energy fraction','physical projection coefficient'],[[s,n,v['cosine'],v['energy_fraction'],v['physical_projection_coefficient']] for s,e in m['errors'].items() if s!='20000' for n,v in e['et_column_projection'].items()])
    add('A useful exact linear decomposition is xi_LS−xi_truth = A⁺e_t + A⁺e_c − 0.02A⁺e_d. The following contributions add to the physical coefficient bias. This is an algebraic decomposition at each fixed checkpoint; A itself changes across checkpoints, so it is not a causal attribution.')
    table(['state','error source','transport bias contribution','diffusion bias contribution'],[[s,k,v[ti[0]],v[ti[1]]] for s,e in m['errors'].items() for k,v in e['coefficient_bias_components'].items()])
    add('Transport bias from target error falls +0.7015→+0.1073; transport-feature and diffusion-feature contributions change +0.3333/−0.1647→−0.02605/+0.01460. At 10k the net feature-induced transport bias is −0.01145, while target-induced bias is +0.10734. For diffusion, the two feature-error contributions are +0.02754 and −0.02712: strong cancellation still matters even though each is large compared with the true diffusion coefficient 0.02.')
    add('## E. Figures and inspection notes\n')
    captions={
    'figure1_error_maps':'Figure 1. Shared full-range symmetric color limits per quantity; no percentile clipping. Error bands follow the steep-gradient region. Large second-derivative discrepancies remain localized at 10k.',
    'figure2_normalized_gram':'Figure 2. Unit-L2, uncentered nine-column Gram matrices; each axis uses the physical feature names in canonical order. Persistent correlations do not imply rank deficiency.',
    'figure2_raw_gram':'Supplement to Figure 2. Raw AᵀA/N with common symmetric-log color scale; mixed physical units make scale domination explicit.',
    'figure3_singular_values':'Figure 3. Normalized and raw spectra shown separately on log axes. Normalized rank remains nine and conditioning does not improve.',
    'figure4_true_spurious_alignment':'Figure 4. Signed cosine with each true term. Some transport alignment weakens, but strong diffusion alternatives persist and strengthen.',
    'figure5_ls_coefficients':'Figure 5. Unconstrained full-library LS on predicted u_t, compared with truth; second panel expands spurious coefficients. Values and small coefficients are fully tabulated above.',
    'figure6_error_projections':'Figure 6. Independent projections onto learned true/spurious spans. Fractions are not additive; closure_error=e_t+e_transport−0.02e_diffusion.',
    'figure7_physical_snapshots':'Figure 7. Shared x grid at t≈0.25, 0.65, 1.0; overlays expose localized steep-gradient errors behind global metrics.'}
    for stem,caption in captions.items():add(f'![{caption}]({stem}.png)\n\n{caption} [PDF]({stem}.pdf)')
    add('## F. Hypothesis assessment\n')
    table(['explanation','assessment'],[
        ['Derivative fidelity','Supported as a contributor: all reported errors fall. A blanket claim that all derivatives became accurate is contradicted by u_xx relative error 0.660 at 10k. A causal sufficiency threshold is unresolved.'],
        ['Feature geometry','Broad improved-conditioning / disappearing-alternatives explanation is contradicted: condition numbers increase, angles shrink, and spurious residual fitting remains strong. Some transport pairwise alignment improves.'],
        ['Error cancellation','Supported for transport-versus-diffusion errors in RHS and diffusion coefficient bias; not supported as improved target-to-RHS error cancellation. Remaining RHS/closure errors are substantial.'],
        ['Target fidelity','Strongly supported as an algebraic contributor, particularly for transport bias, by target swaps and A⁺ error decomposition. Dominant causal driver is unresolved because fields co-evolve.'],
        ['Mixed','Best supported overall: target fidelity, feature fidelity, and spatial error cancellation improve together, without a global identifiability/rank transition.']])
    add('The true directions become more relevant to the learned target and yield much more accurate coefficients; they do not suddenly appear as newly independent library directions. These saved states bracket, but do not resolve, the rapid 8,131–8,631 transport movement. No saved intermediate states establish event ordering, and no gradients, Adam update geometry, or causal interventions are analyzed. One trajectory cannot establish seed reliability. Reference discretization, equal observation weighting, and the nonlinear head constraint limit interpretation.')
    add('## Reproduction, validation, and output contract\n')
    add('From repository root, run:\n\n```bash\nOPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=2 .venv/bin/python runs/run_phase19b_transition_diagnostic.py --out run_results/phase19b_transition_diagnostic_repeat\n```\n\nThe destination must not exist. This evaluates saved states only; the entrypoint never calls a training routine. For artifact-only figure/report regeneration, call `utils.phase19b_transition_plotting.render(out)` and `utils.phase19b_transition_report.render_report(out)`.')
    add('All four checkpoint MSEs at 5k/10k/20k reproduce the archived metrics; feature order and the LS coefficient-bias identity are checked. SHA-256 inventory verifies existing long-horizon files remain unchanged, and the main notebook hash is unchanged. Additional checks validate raw versus normalized LS, symbolic polynomial expansion, and the orthogonal residual-reduction identity. See validation.json. No commit or push was made.')
    add('Artifact directory: `'+str(out.resolve())+'`.\n\n- `report.md`: this standalone report with numerical tables and linked figures.\n- `metrics.json`: complete geometry matrices, spectra, ranks, fits, coefficients, error geometry, canonical fidelity metrics, and trained-head coefficients.\n- `fidelity.csv`, `alignments.csv`, `projections.csv`: tidy numerical tables.\n- `fields.npz`: common grid plus reference/5k/10k/20k fields, permitting independent reanalysis.\n- `config.json`, `validation.json`: numerical conventions, sources, and integrity checks.\n- `figure1_error_maps.{png,pdf}`, `figure2_normalized_gram.{png,pdf}`, `figure2_raw_gram.{png,pdf}`, `figure3_singular_values.{png,pdf}`, `figure4_true_spurious_alignment.{png,pdf}`, `figure5_ls_coefficients.{png,pdf}`, `figure6_error_projections.{png,pdf}`, `figure7_physical_snapshots.{png,pdf}`.\n- `email_summary.txt`: scientific summary sent to the confirmed recipient.\n\nImplementation: `runs/run_phase19b_transition_diagnostic.py`, `utils/phase19b_transition.py`, `utils/transition_geometry.py`, `utils/phase19b_transition_plotting.py`, `utils/phase19b_transition_report.py`. Run documentation: `runs/PHASE19B_TRANSITION.md`.')
    (out/'report.md').write_text('\n'.join(parts))
