"""Standalone scientific report assembled from validated measured artifacts."""
import json
from pathlib import Path
import numpy as np
from utils.phase19b_instrumented_events import numeric

INTERPRETATION = """The trajectory reproduced **exactly** through the transition. The most defensible description is **a coupled transition with observable-specific ordering**: learned u_t direction aligns early, transport accelerates next, and the large improvement in spatial error cancellation follows. Full u_t relative-error reduction does not clearly lead transport. No new rank/separation transition is detected, and optimizer quantities show associations and an early alignment episode rather than an established initiating switch.

The following timing observations answer the main questions without treating relative milestones as physical onsets:

- **Target alignment versus target error:** the 50% net-progress milestone for u_t cosine is 8200, transport magnitude 8425, u_t relative-L2 reduction 8525, RHS relative-L2 reduction 8550, and cancellation-ratio reduction 8775. The cosine lead holds across all five declared milestones; target relative-L2 milestones lag transport by 75–100 steps at 10–75% progress and lead by only 25 at 90%. Thus “u_t leads” is valid for directional alignment, not universally for target fidelity. Direction, amplitude and error cannot be collapsed into one event.
- **Rapid movement and peaks:** the predeclared rapid-transport slope criterion first holds at 8019. The fastest centered 200-step progress windows are centered at 8300 for u_t cosine, 8350/8375 for u_xx/u_x relative error, 8400 for transport, 8525 for RHS error, 8550 for u_t relative error, and 8600 for cancellation. These heavily overlapping windows show coupled evolution, not a sequence of isolated regime switches. The earlier archived fastest 500-step transport window 8131–8631 is reproduced.
- **Cancellation lags:** C is 0.3826 at 7000, 0.3866 at 8000 and 0.3914 at 8250: cancellation initially does not improve even as alignment and transport do. C then falls to 0.3573 at 8500, 0.2781 at loose recovery 8853, and 0.2023 at 10500. Its 10% milestone is 8475, after the rapid-transport criterion; its 50% milestone is 350 steps after transport’s midpoint. Spatial cancellation is a late/co-evolving part of recovery, not a demonstrated precursor.
- **Spatial fidelity is not one clock:** u_x/u_xx relative-error midpoints occur at 8400/8350, modestly before transport’s midpoint, whereas RHS compatibility follows it. Their early milestones are not uniformly earlier than u_t cosine. This does not establish an independent spatial-representation-first mechanism.
- **LS becomes Burgers-like only shortly before the head on its actual learned target:** full learned-feature/learned-u_t LS first meets sustained loose/strong criteria at 8825/9975, compared with exact SymNet crossings 8853/10013. That is a nominal 28/38-step lead at 25-step LS resolution, not a long interval with an already-recovered linear equation waiting for SymNet. Two-term learned-target LS reaches loose at 8700. Reference-target LS is already loose at 7000 (and in the prior 5000 diagnostic), but temporarily loses that criterion around 8000; it tests a different target. Conversely, reference features with the learned target reach loose only at 8950 and never strong by 10500. The target swap remains powerful algebraic evidence, not evidence that the actual learned regression was already recovered.
- **Optimizer observations:** actual updates are aligned with both negative fixed-sample gradients at every regular sampled point from 7825 through 8100, then data alignment turns negative again at 8125. The first 100-step-sustained episode therefore precedes rapid transport, but its cosine with −g_data is small and it is not a permanent switch. The same reversal is visible using training-batch gradients. Median Adam inverse denominator rises smoothly from 440.8 at 7000 to 520.4 at 8150, declines during/after the transition and later rises again; the 90th percentile peaks at 8100. These are measurable optimizer-state changes, not evidence of a sudden initiating preconditioner event. Actual surrogate update norm peaks at 8550 (0.00618), during recovery. The first nonnegative fixed-sample data/PDE gradient cosine sustained for 100 steps occurs only at 9625, well after loose recovery. The weighted PDE/data ratio never falls to one (minimum 1.613); its increase reflects a strongly shrinking data gradient, not necessarily worsening data fit.
- **Geometry:** unit-column condition stays between 6.291 and 6.616 at scheduled transition checkpoints; every library has numerical rank nine at 1e−12. The minimum true/spurious angle stays between 26.35° and 29.30°. Maximum adjacent normalized-condition change is 4.91%, maximum angle change 1.59°; neither declared screen fires. Raw condition grows as physical derivative scales grow. There is no observed sharp improvement in identifiability through conditioning/separation.
- **Loss behavior:** fixed-grid data/PDE/total losses fall from (0.02440, 0.009222, 0.02901) at 7000 to (0.005306, 0.005158, 0.007885) at 8500 and (0.0006283, 0.001501, 0.001379) at 10500. The data-loss decrease accelerates through the coefficient transition; PDE loss decreases with fluctuations. No threshold-step loss discontinuity is needed to explain the scalar record.

| Hypothesis | Assessment | Evidence and limitation |
| --- | --- | --- |
| H1: target-fidelity-first | **Partially supported; broad version unresolved** | Directional cosine leads transport consistently, but target relative error largely co-moves and slightly lags. The data do not establish target improvement as the cause. |
| H2: spatial-representation-first | **Not supported as a general sequence; causal claim unresolved** | Some derivative-error milestones modestly lead transport; RHS compatibility and cancellation do not. An early independent spatial-RHS prerequisite is contradicted by the measured order. |
| H3: coupled transition | **Supported observationally** | Rapid changes overlap in the 8.1k–8.8k region, with modest, observable-dependent offsets and no single leader across all fidelity measures. |
| H4: optimizer transition | **Unresolved** | A small update-alignment episode and gradual Adam scaling changes precede/during acceleration, but no unique sustained initiating switch is established. Gradient-conflict resolution before recovery is contradicted by the late sustained sign event. |
| H5: feature-geometry transition | **Contradicted at the sampled resolution** | Rank stays nine; normalized condition and principal angles show only small smooth/nonmonotone changes. Shorter unsampled fluctuations cannot be excluded. |

These distinctions are temporal precedence (cosine/relative milestones), algebraic compatibility (LS substitutions), and optimization association (gradient/update/Adam curves). **None is causal evidence.** The result does not warrant bifurcation language. Physical onsets earlier than 7000 or a unique noise-independent onset are unresolved; the event table reports declared milestones instead.
"""


def report(out):
    out=Path(out);v=json.loads((out/'validation.json').read_text());cfg=json.loads((out/'config.json').read_text())
    if v['status']!='passed' or not v.get('analysis_passed'):raise RuntimeError('Validated analysis required')
    d=numeric(out/'transition_metrics.csv');g=numeric(out/'gradient_update_metrics.csv');ls=numeric(out/'ls_trajectory.csv')
    geo=numeric(out/'geometry_metrics.csv');ev=json.loads((out/'events.json').read_text());peak=numeric(out/'descriptive_peak_rates.csv')
    parts=[]
    def add(s):parts.append(s+'\n')
    def table(headers,rows):
        def fmt(x):return 'unresolved' if x is None else (f'{x:.7g}' if isinstance(x,float) else str(x))
        add('| '+' | '.join(headers)+' |\n| '+' | '.join(['---']*len(headers))+' |\n'+'\n'.join('| '+' | '.join(fmt(x) for x in r)+' |' for r in rows))
    add('# Phase 19B: temporal ordering during recovery\n')
    add(INTERPRETATION)
    add('## Reproduction gate and preservation\n')
    add(f'The original trajectory **reproduced** over all {v["rows_compared"]:,} scalar rows from step 0 through 10,501. Every row was compared for data/PDE/total loss, all nine physical coefficients, coefficient error and spurious L2; recovery flags were required to match exactly. Tolerance was `abs(new−old) <= 1e−8 + 1e−6*abs(old)`. The extra row at 10,501 validates the actual update leaving the final diagnostic state. This reproduces the required prefix of the 100k run, not its unneeded later tail.')
    table(['quantity','maximum absolute discrepancy, all steps','maximum discrepancy, 5000–10000'],[[k,val,v['interval_5000_10000_max_absolute_error'][k]] for k,val in v['max_absolute_error'].items()])
    table(['archived checkpoint','surrogate tensors bitwise equal','SymNet tensors bitwise equal'],[[r['step'],r['surrogate_bitwise_equal'],r['symnet_bitwise_equal']] for r in v['checkpoint_state_checks']])
    add(f'First exact loose recovery: **{v["first_loose_step"]}**. First exact strong recovery: **{v["first_strong_step"]}**. All original long-horizon and prior post-hoc files were SHA-256 verified unchanged before/after; the main notebook hash also matches. No architecture, regularization, optimizer, loss weight, or batch convention changed. No commit or push is part of this diagnostic.')
    add('## Exact setup, schedule and measurement definitions\n')
    add('Shock-forming Burgers, physical coordinates; SIREN width 64, three hidden layers, frequencies 20/1; original MinimalSymNet. Fixed transferred scales `[0.8564476370811462, 2.418001890182495, 49.38141632080078]`. Adam lr 5e−4, standard betas 0.9/0.999 and epsilon 1e−8, batch 4096, data/PDE weights 1/0.5, no added regularization. Exact original seed-19219 initialization tensors are loaded, rather than regenerated; seed-19220 batch generator is verified against archived batches, then continued. Batch zero is reused at steps 0 and 1. One optimizer step is executed per outer iteration. CPU float32, two Torch threads; software versions and git/source hashes are in provenance.json.')
    add('Full-grid diagnostics: **5000 plus every 25 steps from 7000 through 10500 inclusive, plus 8131, 8631, 8853, 10013**. That is 146 evaluations (145 in the transition). All requested special locations are retained. Additional state/update anchors 0, 50, 200, 500, 1000, 2000 give 152 saved states with their actual following updates. Geometry: 5000, 7000, 7500, 8000, 8250, 8500, 8750, 9000, 9500, 10000, 10500; reference geometry is stored too. Exact lists are in config.json.')
    add('Each saved state at s is before update s→s+1 and after s completed updates. Capture records the exact minibatch, state tensors, optimizer state and batch/global RNG states. It also saves the actual parameter displacement, ordinary combined training gradient, and post-update Adam state. Capture asserts unchanged RNG. Diagnostic gradients are evaluated **offline**, after the entire reproduction gate passes: no extra diagnostic backward/autograd operations are inserted into training. Offline training-batch losses and decomposed gradient sums are cross-checked against their captured counterparts.')
    add('All fidelity, coefficients, losses and LS representation curves use the same archived 252×256 full observation grid (64,512 unweighted points, time-major order). Canonical primitive feature evaluation/metrics are reused through field_metrics/evaluate_primitive_feature_metrics, with physical-coordinate autodiff. The reference is the saved numerical solution, with centered periodic spatial derivatives; reference u_t is its Burgers RHS, not independently measured continuum truth. Relative norms use all fixed grid entries, not time quadrature weights.')
    add('Gradients are evaluated both on the exact varying training minibatch and on fixed indices `floor(arange(4096)*64512/4096)`. The main figure uses the latter for temporal comparability. Actual Adam updates come from the varying training minibatch; their cosine with fixed-sample gradients is an out-of-batch diagnostic. Neither fixed-sample gradients nor their ratios are asserted equal to full-grid gradients. Both versions are retained in gradient_update_metrics.csv.')
    add('For surrogate θ: g_data=∇θL_data, g_PDE=∇θL_PDE, g_total=g_data+0.5g_PDE. Norm ratios are saved both unweighted and weighted; plots label the weighted ratio. Update cosines are with negative gradients. SymNet data gradient is identically zero; its PDE, weighted total, and actual update norms are retained. Adam m̂/v̂ are reconstructed from saved post-update moments. Inverse-denominator quantiles and effective gain `||m̂/(sqrt(v̂)+eps)||/||m̂||` describe adaptive scaling; momentum/gradient and update/momentum cosines distinguish momentum from coordinatewise scaling. Actual float32 displacement is measured by subtraction, so it differs slightly from a float64 formula reconstruction.')
    add('Cancellation is exactly the prior definition: e_c=ûû_x−uu_x, e_d=û_xx−u_xx, e_R=−e_c+0.02e_d; C=||e_R||²/(||e_c||²+0.02²||e_d||²). Lower C means stronger spatial cancellation. We separately save unweighted/weighted diffusion norms. Closure r=û_t−(−ûû_x+0.02û_xx), its MSE/norm, and relative norm versus learned u_t are tracked. This is not the trained-head residual.')
    add('Canonical nine-term physical ordering is `[u,u_x,u_xx,u^2,u*u_x,u*u_xx,u_x^2,u_x*u_xx,u_xx^2]`, checked against MinimalSymNet. All LS uses float64 unit-L2 column normalization (no centering/intercept), SVD cutoff 1e−12, and converts back to physical coefficients. Two-term fits explicitly order transport then diffusion. Raw and normalized geometry are separate; ranks at 1e−12, 1e−8, 1e−4, 1e−2 and spectra/Gram/Pearson matrices are retained. True/spurious angles use thin SVD orthonormal bases. Unconstrained LS is a relaxation, not a replacement or exact model of the nonlinear one-product SymNet optimization.')
    add('## Selected synchronized numerical observations\n')
    selected={5000,7000,7500,8000,8131,8250,8400,8500,8631,8750,8853,9000,9500,10000,10013,10500}
    table(['step','u_t relative L2','u_t cosine','RHS relative L2','cancellation C','transport','diffusion','coefficient error','spurious L2'],[[r[k] for k in ['step','u_t_rel_l2','u_t_cosine','rhs_rel_l2','rhs_cancellation_ratio','xi_u*u_x','xi_u_xx','coefficient_error','spurious_l2']] for r in d if r['step'] in selected])
    table(['step','u relative L2','u_x relative L2','u_xx relative L2','transport relative L2','weighted diffusion relative L2','closure MSE','fixed-grid data MSE','fixed-grid PDE MSE'],[[r[k] for k in ['step','u_rel_l2','u_x_rel_l2','u_xx_rel_l2','transport_rel_l2','weighted_diffusion_rel_l2','closure_mse','fixed_grid_data_loss','fixed_grid_pde_loss']] for r in d if r['step'] in selected])
    add('Full MSE/RMSE/relative L2, cosine, Pearson, prediction/reference RMS for every quantity and state are in transition_metrics.csv. Multiplying u_xx by 0.02 changes dimensional norms/MSE but not its relative L2 or cosine; this is intentional.')
    add('## Event table and timing limits\n')
    add('Criteria were written to config.json before replay. Relative milestones are first 10/25/50/75/90% of the net 7000→10500 change, sustained for 100 steps on the regular 25-step grid. They are endpoint-dependent descriptive markers, not objective physical onset times. Peaks use centered 200-step differences and do not locate an onset. Exact off-grid saved states improve coverage around known events but are excluded from regular-grid timing estimates. All reported ordering must be read alongside these definitions and sensitivity across thresholds.')
    table(['quantity','10%','25%','50%','75%','90%'],[[key]+[next(r['step'] for r in ev if r['event']==key and r['criterion'].startswith(str(p)+'%')) for p in [10,25,50,75,90]] for key in ['u_t_rel_l2','u_t_cosine','u_x_rel_l2','u_xx_rel_l2','transport_rel_l2','rhs_rel_l2','rhs_cancellation_ratio','xi_u*u_x','xi_u_xx']])
    table(['event','criterion','step','status'],[[r[k] for k in ['event','criterion','step','status']] for r in ev if not any(r['criterion'].startswith(str(p)+'%') for p in [10,25,50,75,90])])
    table(['quantity','center of fastest 200-step net-progress rate','normalized progress / step'],[[r['quantity'],r['center_step'],r['normalized_progress_per_step']] for r in peak])
    add('## Least-squares versus learned head\n')
    table(['step','fit','transport','diffusion','residual MSE','coefficient error','spurious L2'],[[r[k] for k in ['step','fit','xi_u*u_x','xi_u_xx','residual_mse','coefficient_error','spurious_l2']] for r in ls if r['step'] in {7000,7500,8000,8500,8853,9000,10000,10500}])
    add('Modes: learned_learned uses learned features/learned u_t; learned_reference swaps only the target; reference_learned swaps only the columns. true_support modes use the two learned true-term columns. These are algebraic substitutions, not interventions on the training trajectory. The full CSV includes all nine physical coefficients, recovery flags, residual norms/rank, and physical coefficient errors.')
    add('## Gradients, updates and Adam state\n')
    table(['step','fixed data/PDE cosine','weighted PDE/data ratio','actual update norm','relative update norm','update / −data','update / −PDE','Adam effective gain','inverse denominator median'],[[r[k] for k in ['step','surrogate_data_pde_cosine','surrogate_weighted_pde_data_ratio','surrogate_update_norm','surrogate_relative_update_norm','surrogate_update_cos_negative_data','surrogate_update_cos_negative_pde','surrogate_effective_preconditioning_gain','surrogate_inverse_denominator_p50']] for r in g if r['sample']=='fixed' and r['step'] in selected])
    table(['step','batch data/PDE cosine','weighted PDE/data ratio','head total gradient norm','head update norm','momentum / batch total gradient','update / −momentum'],[[r[k] for k in ['step','surrogate_data_pde_cosine','surrogate_weighted_pde_data_ratio','symnet_total_gradient_norm','symnet_update_norm','surrogate_momentum_cos_total_gradient','surrogate_update_cos_negative_momentum']] for r in g if r['sample']=='training' and r['step'] in selected])
    add('## Geometry checks\n')
    table(['step','raw condition','unit-column condition','raw rank @1e−12','normalized rank @1e−12','minimum angle (degrees)'],[[r[k] for k in ['step','raw_condition','normalized_condition','raw_rank_1e12','normalized_rank_1e12','principal_angle_min']] for r in geo])
    screens=json.loads((out/'geometry_change_screen.json').read_text())
    table(['from','to','relative normalized-condition change','minimum-angle change (degrees)','screen positive'],[[r[k] for k in ['from_step','to_step','relative_condition_change','angle_change_degrees','screen_positive']] for r in screens])
    add('The geometry screen is a declared coarse sampling rule, not a test for a mathematical bifurcation. Shorter events between its checkpoints remain unresolved. Full pairwise alignments and singular spectra are in geometry.json/geometry_metrics.csv.')
    add('## Figures and captions\n')
    captions={
      'figure1_synchronized_transition':'Synchronized full-grid target/spatial fidelity, physical coefficients, fixed-grid losses, fixed-sample gradients and actual minibatch updates. Gray span: fastest archived transport window 8131–8631; dotted green/purple: loose 8853/strong 10013. Transport and diffusion use labeled separate axes. The final panel separates gradient ratio and relative update scales.',
      'figure2_representation_evolution':'Target and Burgers-RHS error maps at 7500/8000/8500/9000/10000. Shared full-range symmetric color limits across states within each row; no percentile clipping or per-state autoscaling. Errors are prediction minus numerical reference on the shared physical grid.',
      'figure3_ls_vs_symnet':'Physical LS and learned-head coefficients. Reference-target/reference-feature swaps diagnose algebraic compatibility; unconstrained LS differs from the trained head and does not prove reachability.',
      'figure4_adam_geometry':'Fixed-sample gradient norms; actual post-update Adam inverse-denominator quantiles and effective gain; actual-batch momentum alignment and update/momentum alignment. Coordinate quantiles describe optimizer state, not a change in learning rate.',
      'figure5_feature_geometry':'Raw and unit-column condition numbers and minimum true/spurious principal angle at the declared subset. Raw units differ between columns. Geometry changes are observational.',
      'figure6_spatial_fidelity':'Relative errors of all spatial quantities plus dimensional weighted error/closure norms. u_xx and 0.02u_xx relative errors coincide mathematically.'}
    for stem,caption in captions.items():add(f'![{caption}]({stem}.png)\n\n{caption} [Vector PDF]({stem}.pdf)')
    add('## Caveats and provenance\n')
    add('Temporal precedence is not causality. This is one exact joint trajectory, not a controlled intervention or seed comparison. Target, spatial fields, and coefficients share an evolving surrogate. Observation begins densely at 7000, so earlier gradual changes are left-censored; there is only a 5000 anchor outside this interval. Timing depends on the observable and milestone definition. Fixed gradient sampling is deterministic but sparse relative to the full grid; actual minibatch directions remain noisy. Coarse feature-geometry sampling cannot exclude shorter fluctuations. Numerical-reference/operator discrepancies persist at steep gradients. Large raw u_xx MSE does not imply equally poor weighted RHS fidelity. Conversely, coefficient recovery and small learned-head PDE loss do not imply accurate derivatives. No bifurcation or causal mechanism is inferred.')
    add('All scalar and field plots can be reconstructed from the saved CSV/NPZ files. Saved pre-update models, minibatches, optimizer states and actual updates permit independent gradient and full-field re-evaluation. Original artifact hashes, package versions, source hashes and reproduction checks are in provenance.json/validation.json; endpoint field and cancellation checks agree with the previous 5k/10k diagnostic.')
    add('## Artifacts and exact reproduction command\n')
    add('Root: `'+str(out.resolve())+'`.\n\n- `report.md`, `config.json`, `validation.json`, `provenance.json`.\n- `optimization_history.csv`, `reproduction_errors.csv`: every step 0–10501.\n- `transition_metrics.csv`: 146 fixed-grid diagnostic states.\n- `gradient_update_metrics.csv`: 292 rows (training/fixed samples).\n- `ls_trajectory.csv`: 730 rows (five linear comparisons/state).\n- `geometry_metrics.csv`, `geometry.json`: subset plus numerical matrices/spectra.\n- `events.csv`, `events.json`, `descriptive_peak_rates.csv`, `geometry_change_screen.json`.\n- `states/state_*.pt`, `updates/update_*.pt` (152 each).\n- `fixed_gradient_indices.npy`, `snapshot_fields.npz`.\n- Six `figure*.png` and matching `figure*.pdf` files linked above.\n- `artifact_manifest.json`: final generated-file hashes and implementation hashes, added after inspection.\n\nProtocol: `runs/PHASE19B_TRANSITION_INSTRUMENTED.md`.')
    add('```bash\nOPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=2 .venv/bin/python -u runs/run_phase19b_transition_instrumented.py --out run_results/phase19b_transition_instrumented_repeat\n```\n\nThe destination must not exist. To analyze a completed replay without retraining, use `--stage analyze` on its directory (analysis tables must not already exist). To regenerate only plots/report, call `utils.phase19b_instrumented_plotting.render(out)` and `utils.phase19b_instrumented_report.report(out)`.')
    (out/'report.md').write_text('\n'.join(parts))
